export const networkJson = {
  id: 'httpcall_1',
  name: '重新计算商品价格',
  description: '',
  callArguments: {
    method: 'POST',
    url: 'http://localhost:5141/goods/edit',
    contentType: 'application/json',
    pathParameters: null,
    queryParameters: null,
    cookies: null,
    headers: null,
    form: {
      name: '$goodsDto.name',
      goodsId: '$goodsDto.goodsId',
      price: '$goodsDto.price',
    },
    body: '$goodsDtoStr',
    Authorizetion: {
      type: 'Basic',
      username: 'api',
      password: '',
      token: '',
    },
  },
  result: '$call_response',
}

export const networkJsonSchema = {
  $schema: 'https://json-schema.org/draft/2019-09/schema',
  $id: 'http://example.com/example.json',
  type: 'object',
  default: {},
  title: 'Root Schema',
  required: ['id', 'name', 'description', 'callArguments', 'result'],
  properties: {
    id: {
      type: 'string',
      default: '',
      title: 'The id Schema',
      examples: ['httpcall_1'],
    },
    name: {
      type: 'string',
      default: '',
      title: 'The name Schema',
      examples: ['重新计算商品价格'],
    },
    description: {
      type: 'string',
      default: '',
      title: 'The description Schema',
      examples: [''],
    },
    callArguments: {
      type: 'object',
      default: {},
      title: 'The callArguments Schema',
      required: [
        'method',
        'url',
        'contentType',
        'pathParameters',
        'queryParameters',
        'cookies',
        'headers',
        'form',
        'body',
        'Authorizetion',
      ],
      properties: {
        method: {
          type: 'string',
          default: '',
          title: 'The method Schema',
          examples: ['POST'],
        },
        url: {
          type: 'string',
          default: '',
          title: 'The url Schema',
          examples: ['http://localhost:5141/goods/edit'],
        },
        contentType: {
          type: 'string',
          default: '',
          title: 'The contentType Schema',
          examples: ['application/json'],
        },
        pathParameters: {
          type: 'null',
          default: null,
          title: 'The pathParameters Schema',
          examples: [null],
        },
        queryParameters: {
          type: 'null',
          default: null,
          title: 'The queryParameters Schema',
          examples: [null],
        },
        cookies: {
          type: 'null',
          default: null,
          title: 'The cookies Schema',
          examples: [null],
        },
        headers: {
          type: 'null',
          default: null,
          title: 'The headers Schema',
          examples: [null],
        },
        form: {
          type: 'object',
          default: {},
          title: 'The form Schema',
          required: ['name', 'goodsId', 'price'],
          properties: {
            name: {
              type: 'string',
              default: '',
              title: 'The name Schema',
              examples: ['$goodsDto.name'],
            },
            goodsId: {
              type: 'string',
              default: '',
              title: 'The goodsId Schema',
              examples: ['$goodsDto.goodsId'],
            },
            price: {
              type: 'string',
              default: '',
              title: 'The price Schema',
              examples: ['$goodsDto.price'],
            },
          },
          examples: [
            {
              name: '$goodsDto.name',
              goodsId: '$goodsDto.goodsId',
              price: '$goodsDto.price',
            },
          ],
        },
        body: {
          type: 'string',
          default: '',
          title: 'The body Schema',
          examples: ['$goodsDtoStr'],
        },
        Authorizetion: {
          type: 'object',
          default: {},
          title: 'The Authorizetion Schema',
          required: ['type', 'username', 'password', 'token'],
          properties: {
            type: {
              type: 'string',
              default: '',
              title: 'The type Schema',
              examples: ['Basic'],
            },
            username: {
              type: 'string',
              default: '',
              title: 'The username Schema',
              examples: ['api'],
            },
            password: {
              type: 'string',
              default: '',
              title: 'The password Schema',
              examples: [''],
            },
            token: {
              type: 'string',
              default: '',
              title: 'The token Schema',
              examples: [''],
            },
          },
          examples: [
            {
              type: 'Basic',
              username: 'api',
              password: '',
              token: '',
            },
          ],
        },
      },
      examples: [
        {
          method: 'POST',
          url: 'http://localhost:5141/goods/edit',
          contentType: 'application/json',
          pathParameters: null,
          queryParameters: null,
          cookies: null,
          headers: null,
          form: {
            name: '$goodsDto.name',
            goodsId: '$goodsDto.goodsId',
            price: '$goodsDto.price',
          },
          body: '$goodsDtoStr',
          Authorizetion: {
            type: 'Basic',
            username: 'api',
            password: '',
            token: '',
          },
        },
      ],
    },
    result: {
      type: 'string',
      default: '',
      title: 'The result Schema',
      examples: ['$call_response'],
    },
  },
  examples: [
    {
      id: 'httpcall_1',
      name: '重新计算商品价格',
      description: '',
      callArguments: {
        method: 'POST',
        url: 'http://localhost:5141/goods/edit',
        contentType: 'application/json',
        pathParameters: null,
        queryParameters: null,
        cookies: null,
        headers: null,
        form: {
          name: '$goodsDto.name',
          goodsId: '$goodsDto.goodsId',
          price: '$goodsDto.price',
        },
        body: '$goodsDtoStr',
        Authorizetion: {
          type: 'Basic',
          username: 'api',
          password: '',
          token: '',
        },
      },
      result: '$call_response',
    },
  ],
}
